"""Public API for the photonics simulator."""

from .analysis import (
    AveragePower,
    HarmonicResponse,
    estimate_average_power,
    estimate_harmonic_response,
)
from .config import (
    BoundaryConfig,
    FieldMonitorConfig,
    FluxMonitorConfig,
    GridConfig,
    InitialConditionConfig,
    MaterialConfig,
    SimulationConfig,
    SourceConfig,
    TimeConfig,
    VisualizationConfig,
    create_default_config,
)
from .geometry import (
    create_circular_mask,
    create_elliptical_mask,
    create_grid_coordinate_arrays,
    create_rectangular_mask,
    validate_geometry_mask,
    create_polygon_mask,
)
from .materials import (
    MaterialMap,
    MaterialRegion,
    add_circular_region,
    add_elliptical_region,
    add_masked_region,
    add_rectangular_region,
    add_physical_rectangular_region,
    create_background_refractive_index_array,
    create_material_map_from_refractive_index,
    create_planar_interface_material_map,
    create_rectangular_material_map,
    create_uniform_material_map,
    validate_material_map,
    validate_refractive_index_array,
    add_polygonal_region,
    compose_material_regions,
)
from .monitors import FieldMonitorState, FluxMonitorState
from .solver import SimulationState, Wave2DSimulation


__all__ = [
    "AveragePower",
    "BoundaryConfig",
    "FieldMonitorConfig",
    "FieldMonitorState",
    "FluxMonitorConfig",
    "FluxMonitorState",
    "GridConfig",
    "HarmonicResponse",
    "InitialConditionConfig",
    "MaterialConfig",
    "MaterialMap",
    "MaterialRegion",
    "SimulationConfig",
    "SimulationState",
    "SourceConfig",
    "TimeConfig",
    "VisualizationConfig",
    "Wave2DSimulation",
    "add_masked_region",
    "add_rectangular_region",
    "create_background_refractive_index_array",
    "create_default_config",
    "create_grid_coordinate_arrays",
    "create_material_map_from_refractive_index",
    "create_planar_interface_material_map",
    "create_rectangular_material_map",
    "create_uniform_material_map",
    "estimate_average_power",
    "estimate_harmonic_response",
    "validate_geometry_mask",
    "validate_material_map",
    "validate_refractive_index_array",
    "add_circular_region",
    "add_elliptical_region",
    "create_circular_mask",
    "create_elliptical_mask",
    "add_physical_rectangular_region",
    "create_rectangular_mask",
    "add_polygonal_region",
    "create_polygon_mask",
    "compose_material_regions",
]
